#' Data dimensionality reduction using PCA on a split object.
#'
#' @description
#' Fit PCA on the training set and apply the same transformation to the test 
#' set. The goal is to use principal components in prediction models as a 
#' smaller number of variables instead of all the marker predictors.
#'
#' @param split An object of class \code{split}, corresponding to one element of
#'   the total `cv_object` generated by one of the functions [predict_cv0()],
#'   [predict_cv1()], or [predict_cv2()], and containing the following items:
#' * **training**: \code{data.frame} Training dataset
#' * **test**: \code{data.frame} Test dataset
#'
#' @param geno_data \code{data.frame} An element named `geno` within an object of
#'   class `METData`.
#'
#' @return pc_values A \code{data.frame} containing the principal components
#'   in columns and the names of all lines used in the study is contained in the
#'   first column 'geno_ID'. PCs for the lines present in the test set were
#'   computed based on the transformation done on the training set.
#'
#' @author Cathy C. Jubin \email{cathy.jubin@@uni-goettingen.de}
#' @export
#'
#'
#'


apply_pca <- function(split, geno_data, num_pcs) {
  geno_data$geno_ID = row.names(geno_data)
  
  geno_data_training = geno_data[geno_data$geno_ID%in%unique(split[[1]][,'geno_ID']),]
  geno_data_training = unique(geno_data_training)
  geno_data_test =  geno_data[geno_data$geno_ID%in%unique(split[[2]][,'geno_ID']),]
  geno_data_test = unique(geno_data_test)
  
  
  rec <- recipe(geno_ID ~ . ,
                data = geno_data_training) %>%
    update_role(geno_ID, new_role = 'outcome') %>%
    step_nzv(all_predictors()) %>%
    step_pca(all_predictors(),
             num_comp = num_pcs,
             options = list(center = T, scale. = T))
  
  norm_obj <- prep(rec, training = geno_data_training,strings_as_factors = FALSE)
  
  training_pca <- bake(norm_obj, geno_data_training)
  test_pca <- bake(norm_obj, geno_data_test)
  
  training <-
    merge(split[[1]], training_pca, by = 'geno_ID', all.x = T)
  
  test <-
    merge(split[[2]], test_pca, by = 'geno_ID', all.x = T)
  
  
  return(list(training,test))
  
}